// AT END "-" added means incomplete
// without "-" means already completed keys
module.exports = {
    CATEGORIES: "APP-WF-CATEGORIES",
    DEVICE_WATCHFACE_DATA: "APP-WF-DEVICE-WATCHFACE-DATA-", // All Watch faces device wise
    TOP_DOWNLOADED: "APP-WF-DEVICE-TOP-DOWNLOADED-", // Add Device ID Also
    NEWLY_ADDED: "APP-WF-NEWLY-ADDED-", // Add Device ID Also
    RECENTLY_USED: "APP-WF-RECENTLY-USED-", // ADD device Id(P0) and user Id(P1)
    RANDOM_WATCHFACES: "APP-WF-RANDOM-", // ADD Device Id
    "USER-MYFAV": "APP-WF-MYFAV-", // ADD User Id  APP-MYFAV-57-USERID-252784
    "IN-USE-COUNT": "APP-WF-IN-USE-COUNT-", // ADD WATCHFACE Id
    "IN-BUILT-LIST": "APP-WF-IN-BUILT-LIST-", // ADD DEVICE ID
    "LIST-BY-CATEGORY": "APP-WF-LIST-BY-CATEGORY-", // ADD DEVICE ID
    "CATEGORY-DETAIL": "APP-WF-CATEGORY-DETAIL-", //  deviceId+"-CATEGORY-ID-"+categoryId;
    WATCHFACE_DETAIL: "APP-WF-DETAILS-", // deviceId+"-WFID-"+watchfaceId;
    "7-DAYS": 24 * 60 * 60 * 7,
    "1-DAY": 24 * 60 * 60,
    "CW-CATEGORIES": "APP-WF-CW-CATEGORIES",
    "CW-MASTER": "APP-WF-CW-MASTER",
    "CW-LIST": "APP-WF-CW-LIST-", // add device id
    "CW-FONT-STYLE": "APP-WF-CW-FONT-STYLE",
    WATCHFACE_LIST: "APP-WF-LIST-", // add device_id + "-" + firmware_id
    // ==============V2====================
    RANDOM_WATCHFACES_V2: "APP-WF-V2-RANDOM-", // ADD Device Id
    "1-HOUR": 60 * 60,
    "USER-MYFAV-V2": "APP-WF-V2-MYFAV-",
    "POPULAR-LIST": "APP-WF-V2-POPULAR-LIST-", // ADD DEVICE ID
    TRENDING: "APP-WF-TRENDING-",
    WATCHFACE_RATING: "APP-WF-RATING", // + watchface_id;
    USER_WATCHFACE_RATED: "APP-WF-IS-RATED-", // watchface_id + user_id
    DEVICE_WATCHFACE_LIST: "APP-WF-DEVICE-WATCHFACE-LIST-", // device_id
    USER_CREATIONS: "APP-WF-CW-USER-CREATIONS-", //USER ID AND DEVICE_ID
    NEWLY_ADDED_V2: "APP-WF-V2-NEWLY-ADDED-", // ADD DEVICEID
    WATCHFACE_MASTER: "APP-WF-MASTER-", // ADD WATCHFACE ID
    CONSTANTS: "APP-WF-CONSTANTS",
    "LIST-BY-CATEGORY": "APP-WF-LIST-BY-CATEGORY-", // ADD DEVICE ID
    "NPL-WATCHFACE": "APP-WF-NPL-WATCHFACE-", // add device id,
    FIRMWARE_WATCHFACE_DATA: "APP-WF-FIRMWARE-WATCHFACE-DATA-", // All Watch faces FIRMWARE WISE,
    DIY_LIST:"APP-WF-DIY-LIST-", // ADD DEVICE ID
    "CATEGORY-DETAIL-V2": "APP-WF-V2-CATEGORY-DETAIL-", //  deviceId+"-CATEGORY-ID-"+categoryId;

};
